name: Haskell CI

on: [push]

jobs:
  sync-upstream:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
    - name: Sync from upstream
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "kadena-io/chainweb-node"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build master with ${{ matrix.ghc }} / ${{ matrix.cabal }} on ${{ matrix.os }}
    needs: ['sync-upstream']
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.1']
        cabal: ['3.0']
        os: ['ubuntu-18.04']
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.cabal_cache_aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.cabal_cache_aws_secret_access_key }}
      CABAL_CACHE: "$HOME/bin/cabal-cache"

    steps:
    - uses: actions/checkout@v1
      with:
        ref: "master"
    - name: Install cabal-cache (ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: |
        mkdir -p "$HOME/bin"
        curl -Ls "https://github.com/haskell-works/cabal-cache/releases/download/v1.0.1.1/cabal-cache_x86_64_linux.tar.gz" | tar -xzC "$HOME/bin/"
        
    - name: Setup Haskell (ubuntu)
      if: contains(matrix.os, 'ubuntu')
      uses: actions/setup-haskell@v1
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Install non-Haskell dependencies (ubuntu)
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt-get install -y git librocksdb-dev zlib1g-dev libtinfo-dev libsqlite3-dev libz3-dev z3
    - name: Create cabal.project.local (ghc-8.8.1)
      if: matrix.ghc == '8.8.1'
      run: |
        cat > cabal.project.local <<EOF
        package chainweb
          ghc-options: -Wwarn
          haddock-options: --optghc=-Wwarn

        package chainweb
          ghc-options: -fwrite-ide-info
          ghc-options: -hiedir ./dist-newstyle/hie
          documentation: true

        package pact
          ghc-options: -Wwarn
          haddock-options: --optghc=-Wwarn

        package vault
          documentation: false

        source-repository-package
          type: git
          location: http://github.com/larskuhtz/ixset-typed.git
          tag: 335c8e31d39be873a429fc9814060bf928ad0ee9

        source-repository-package
          type: git
          location: http://github.com/osa1/data-dword.git
          tag: 573d7b5fdd3635ade9bc1cf8fd88a1bf8059f78f

        source-repository-package
          type: git
          location: http://github.com/LeventErkok/sbv.git
          tag: 2476a36316e00df40061f9257528f4df6f324927

        allow-newer:
          asn1-encoding:base
          compactable:base
          fake:*
          ixset-typed:safecopy
          ixset-typed:template-haskell
          pact:*
          paths:*
          safecopy:template-haskell
          strict-tuple:base
          these:*
          token-bucket:base
          chainweb:systemd
        EOF
    - name: Create cabal.project.local (not ghc-8.8.1)
      if: matrix.ghc != '8.8.1'
      run: |
        cat > cabal.project.local <<EOF
        package chainweb
          documentation: true
        allow-newer:
          chainweb:systemd
        EOF
    - name: Fix cabal.project
      run: sed -i -e '/swagger2 < 2.4/d' cabal.project
    - name: Update package database
      run: cabal v2-update
    - name: Configure build
      run: cabal v2-configure --enable-tests
    - name: Sync from cabal cache
      run: $CABAL_CACHE sync-from-archive --threads 16 --archive-uri s3://cabal-cache/${{ matrix.os }} --region us-east-1
    - name: Install build dependencies
      run: cabal v2-build --only-dependencies
    - name: Sync to cabal cache
      run: $CABAL_CACHE sync-to-archive --threads 16 --archive-uri s3://cabal-cache/${{ matrix.os }} --region us-east-1
    - name: Build
      run: cabal v2-build --enable-tests
    - name: Sync to cabal cache
      run: $CABAL_CACHE sync-to-archive --threads 16 --archive-uri s3://cabal-cache/${{ matrix.os }} --region us-east-1
    - name: Install test dependencies
      run: $CABAL_CACHE v2-build --only-dependencies --enable-tests
    - name: Sync to cabal cache
      run: $CABAL_CACHE sync-to-archive --threads 16 --archive-uri s3://cabal-cache/${{ matrix.os }} --region us-east-1
    - name: Run tests
      run: cabal v2-run chainweb-tests -- --hide-successes

    - name: Prepare artifacts
      run: |
        mkdir -p dist-newstyle/artifacts/applications
        mkdir -p dist-newstyle/artifacts/docs
        cp dist-newstyle/build/*/ghc-${{ matrix.ghc }}/chainweb-*/build/*/{chainweb-miner,chainweb-node,cwtool} dist-newstyle/artifacts/applications
        cp -r dist-newstyle/build/*/ghc-${{ matrix.ghc }}/chainweb-*/doc/html/chainweb dist-newstyle/artifacts/docs
    - name: Publish applications
      uses: actions/upload-artifact@v1
      with:
        name: chainweb-applications
        path: dist-newstyle/artifacts/applications
    - name: Publish hie files (only ghc-8.8.1)
      if: matrix.ghc == '8.8.1'
      uses: actions/upload-artifact@v1
      with:
        name: hie-files
        path: dist-newstyle/hie
    - name: Publish API documentation
      uses: actions/upload-artifact@v1
      with:
        name: api-documentation
        path: dist-newstyle/artifacts/docs
  
    # TODO
    # 
    # * [x] upload artifacts: binaries, docs
    # * [x] job that syncs master from main repo and runs build
    # * [x] cabal-cache (or docker volumne on github package registry?)
    # * [ ] docker build (publish to github registry and/or docker registry)
    # * [ ] upload binaries to S3
    # * [ ] publish documentation to github pages
    # * [ ] run slow tests
    # * [ ] mac builds
    # * [ ] windows build
    # * [ ] add schedule
