name: Haskell CI

on: [push]

jobs:
  build:
    name: Build with ${{ matrix.ghc }} / ${{ matrix.cabal }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.1']
        cabal: ['3.0']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}
    - name: Create cabal.project.local
      run: touch cabal.project.local
    - name: Update package database
      run: cabal v2-update
    - name: Install build dependencies
      run: cabal v2-build --only-dependencies
    - name: Build
      run: cabal v2-build --enable-tests
    - name: Install test dependencies
      run: cabal v2-build --only-dependencies --enable-tests
    - name: Run tests
      run: cabal v2-test --enable-tests
