name: "Nix build"
on:
  schedule:
  - cron: '0 */6 * * *'
  pull_request:
  push:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - name: install nix cache
      run: |
        sudo cat >> /etc/nix/nix.conf <<EOF
        substituters = http://nixcache.kadena.io https://nixcache.reflex-frp.org https://cache.nixos.org/
        trusted-public-keys = kadena-cache.local-1:8wj8JW8V9tmc5bgNNyPM18DYNA1ws3X/MChXh1AQy/Q= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
        EOF
    - run: nix-build
