name: "Nix build"
on:
  schedule:
  - cron: '0 */6 * * *'
  pull_request:
  push:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - run: nix-build
